{% set name = "windninja" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/firelab/windninja/archive/refs/tags/{{ version }}.tar.gz
  sha256: e2cf3c4fad8745fd3d763648bfbcfc0558c912fdb872ac5d92261e4364d71d6f

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
    - llvm-openmp  # [osx or win]
    - libgomp  # [linux]
  host:
    - libboost-devel
    - libgdal
    - libnetcdf
    - llvm-openmp  # [osx or win]
    - libgomp  # [linux]

test:
  commands:
    - test -f ${PREFIX}/bin/WindNinja_cli


about:
  home: https://github.com/firelab/windninja
  doc_url: https://weather.firelab.org/windninja/tutorials/
  summary: 'A diagnostic wind model developed for use in wildland fire modeling. '
  description: |
    WindNinja is a diagnostic wind model developed for use in wildland fire modeling.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt


extra:
  recipe-maintainers:
    - jomey
    - Chrismarsh
    - nwagenbrenner
