{% set name = "windninja" %}
{% set version = "3.13.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/firelab/windninja/archive/refs/tags/{{ version }}.tar.gz
  sha256: 42372e3bb653a9e2194d78cc2c868208a9e7a6df44d2d51b6f0bbc5f121ecb5b

build:
  number: 3
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
    - llvm-openmp  # [osx or win]
    - libgomp  # [linux]
  host:
    - libboost-devel
    - libgdal
    - libnetcdf
    - llvm-openmp  # [osx or win]
    - libgomp  # [linux]

test:
  commands:
    - test -f ${PREFIX}/bin/WindNinja_cli


about:
  home: https://github.com/firelab/windninja
  doc_url: https://weather.firelab.org/windninja/tutorials/
  summary: 'A diagnostic wind model developed for use in wildland fire modeling. '
  description: |
    WindNinja is a diagnostic wind model developed for use in wildland fire modeling.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt


extra:
  recipe-maintainers:
    - jomey
    - Chrismarsh
    - nwagenbrenner
